a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("The sum of %d and %d is %d" % (a, b, a + b))
print("The difference of %d and %d is %d" % (a, b, a - b))
print("The product of %d and %d is %d" % (a, b, a * b))
print("The division of %d and %d is %f" % (a, b, a / b))
print("The exponent of %d and %d is %d" % (a, b, a**b))
print("The mod of %d and %d is %d" % (a, b, a % b))
print("The floor of %d and %d is %d" % (a, b, a // b))
